# Generated by Django 6.0.2 on 2026-02-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., DRM, CH, BOTH', max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq_number', models.CharField(blank=True, help_text='e.g. BUILDING, MOVABLE', max_length=50, null=True, verbose_name='SQ No')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Male/Female')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('professional_profile', models.TextField(blank=True, verbose_name='Professional Profile')),
                ('specific_expertise_details', models.TextField(blank=True, verbose_name='Specific Expertise Details')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobile')),
                ('insurance_code', models.CharField(blank=True, max_length=100, verbose_name='Code for Insurance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('private_notes', models.TextField(blank=True, verbose_name='Private E-mail/Other Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Country')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution', verbose_name='Institution')),
                ('primary_expertise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expertisetype', verbose_name='Main Expertise (DRM/CH)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel List',
            },
        ),
    ]
