# Generated by Django 6.0.2 on 2026-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='sq_number',
            field=models.CharField(blank=True, choices=[('BUILDING', 'BUILDING'), ('MOVABLE', 'MOVABLE'), ('OBSERVER', 'OBSERVER')], max_length=50, null=True, verbose_name='SQ Type'),
        ),
    ]
