# Generated by Django 6.0.2 on 2026-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobtitle_alter_personnel_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='job_title',
        ),
        migrations.AddField(
            model_name='personnel',
            name='job_titles',
            field=models.ManyToManyField(blank=True, help_text='Select multiple or create new ones.', to='core.jobtitle', verbose_name='Job Titles'),
        ),
    ]
