# Generated by Django 6.0.2 on 2026-02-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_personnel_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sector Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3388ff', max_length=7, verbose_name='Map Color')),
                ('location_data', models.TextField(blank=True, null=True, verbose_name='Map Coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Worksite Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('location_data', models.TextField(blank=True, null=True, verbose_name='Map Coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksites', to='core.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
