# Generated by Django 6.0.2 on 2026-02-08 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sector_worksite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time (Completion)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Mission Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.team', verbose_name='Assigned Team')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.worksite', verbose_name='Target Worksite')),
            ],
            options={
                'verbose_name': 'Operation Assignment',
                'verbose_name_plural': 'Operation Assignments',
                'ordering': ['-start_time'],
            },
        ),
    ]
