# Generated by Django 6.0.2 on 2026-02-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(blank=True, max_length=150, verbose_name='Team Leader Name')),
                ('editor_name', models.CharField(max_length=150, verbose_name='Editor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_code', models.CharField(max_length=50, verbose_name='Building Code')),
                ('building_name', models.CharField(max_length=150, verbose_name='Name of Building')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('description_matrix', models.JSONField(default=dict, verbose_name='Description Matrix')),
                ('surface_area', models.FloatField(blank=True, null=True, verbose_name='Surface Area (m2)')),
                ('avg_height', models.FloatField(blank=True, null=True, verbose_name='Avg Height (m)')),
                ('floors_above', models.IntegerField(default=1, verbose_name='Storeys Overground')),
                ('floors_below', models.IntegerField(default=0, verbose_name='Storeys Underground')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume (m3)')),
                ('construction_age', models.CharField(blank=True, max_length=100, verbose_name='Age')),
                ('structural_elements', models.JSONField(default=dict, verbose_name='Structural Elements')),
                ('non_structural_elements', models.JSONField(default=dict, verbose_name='Non-Structural Elements')),
                ('cultural_elements', models.JSONField(default=dict, verbose_name='Cultural Elements')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='core.assignment')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(blank=True, max_length=150, verbose_name='Team Leader Name')),
                ('editor_name', models.CharField(max_length=150, verbose_name='Editor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard_type', models.CharField(choices=[('SEISMIC', 'Seismic'), ('FIRE', 'Fire'), ('HYDRO', 'Meteorological/Hydro')], max_length=20)),
                ('event_details', models.JSONField(blank=True, default=dict, verbose_name='Event Params')),
                ('structural_damage', models.JSONField(default=dict, verbose_name='Structural Damage Matrix')),
                ('non_structural_damage', models.JSONField(default=dict, verbose_name='Non-Structural Damage Matrix')),
                ('overall_damage', models.CharField(choices=[('NONE', 'No Damage'), ('LIGHT', 'Light/Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('COLLAPSED', 'Collapsed')], default='NONE', max_length=20)),
                ('intervention_needs', models.JSONField(default=dict, verbose_name='Securing Interventions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='core.assignment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='core.buildinginventory')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntangibleHeritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(blank=True, max_length=150, verbose_name='Team Leader Name')),
                ('editor_name', models.CharField(max_length=150, verbose_name='Editor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_name', models.CharField(max_length=255, verbose_name='Name of Element')),
                ('community_contact', models.CharField(blank=True, max_length=255, verbose_name='Community Contact')),
                ('description_data', models.JSONField(default=dict, verbose_name='Description Data')),
                ('impact_data', models.JSONField(default=dict, verbose_name='Impact Data')),
                ('assistance_needs', models.JSONField(default=dict, verbose_name='Assistance Needs')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='core.assignment')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovableHeritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(blank=True, max_length=150, verbose_name='Team Leader Name')),
                ('editor_name', models.CharField(max_length=150, verbose_name='Editor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_name', models.CharField(max_length=200, verbose_name='Object Name')),
                ('category', models.CharField(max_length=100, verbose_name='Type (Painting, Sculpture etc.)')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Quantity')),
                ('description_details', models.JSONField(default=dict, verbose_name='Materials & Details')),
                ('damage_condition', models.JSONField(default=dict, verbose_name='Damage Condition')),
                ('evacuation_needs', models.JSONField(default=dict, verbose_name='Needs & Evacuation')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='core.assignment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.buildinginventory')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovableTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(verbose_name='Date of transfer')),
                ('team_id', models.CharField(max_length=50, verbose_name='Team ID')),
                ('responsible_person', models.CharField(max_length=150, verbose_name='Responsible')),
                ('from_location', models.CharField(max_length=255, verbose_name='From (Floor/Room)')),
                ('to_location', models.CharField(max_length=255, verbose_name='To (Storage Site)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.movableheritage')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.CharField(blank=True, max_length=150, verbose_name='Team Leader Name')),
                ('editor_name', models.CharField(max_length=150, verbose_name='Editor Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_reference_code', models.CharField(blank=True, max_length=50, verbose_name='Site Ref Code')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='Municipality')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('access_notes', models.TextField(blank=True, verbose_name='Access to site')),
                ('site_type', models.CharField(choices=[('ARCH_ELEMENT', 'Architectural element'), ('COMPLEX', 'Heritage complex'), ('ARCHAEOLOGICAL', 'Archaeological site'), ('OTHER', 'Other')], max_length=50, verbose_name='Type of site')),
                ('number_of_buildings', models.IntegerField(default=1, verbose_name='Number of buildings')),
                ('description_details', models.JSONField(default=dict, verbose_name='Description Details')),
                ('is_protected', models.CharField(choices=[('YES', 'Protected'), ('NO', 'Not Protected'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Legal Protection')),
                ('has_intangible_link', models.BooleanField(default=False, verbose_name='Intangible CH Connection')),
                ('hazard_data', models.JSONField(default=dict, verbose_name='Hazard Data')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to='core.assignment')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='buildinginventory',
            name='site_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.siteassessment'),
        ),
    ]
