# Generated by Django 6.0.2 on 2026-02-08 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buildinginventory_damageassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_team', to='core.personnel', verbose_name='Team Leader'),
        ),
    ]
