# Generated by Django 6.0.2 on 2026-02-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='worksite',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open / Active'), ('COMPLETED', 'Completed / Closed')], default='OPEN', max_length=20, verbose_name='Worksite Status'),
        ),
    ]
